name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker Image
      run: |
        env
        docker build . -t docker.pkg.github.com/${{ github.repository }}/actions
        echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ GITHUB_ACTOR }} --password-stdin docker.pkg.github.com
        docker push docker.pkg.github.com/${{ github.repository }}/actions